dist: xenial
sudo: false
notifications:
  email: false

language: python
python:
  - "3.6"
  - "3.8"
  - "3.9"

install:
  - make install-requirements
  - make install-django-requirements
  - make install-test-requirements

before_script:
  - make lint

script:
  - make coverage
  - codecov

